### ISSUE TITLE
Dependency not available in Maven repository

### ISSUE THREAD

**Issue by StephanBeutel** [RobWin/swagger2markup#1]
Hello,

the swagger2markup dependency is not available in the http://oss.jfrog.org/ repository.
Only the io/swagger2markup folder exists.

**Comment by RobWin** [comment]
Hello,

yes. I'm working not it.

**Comment by RobWin** [comment]
Does this maven repository work for you, until it works with http://oss.jfrog.org/ and Maven central?

```xml
<repository>
<snapshots>
<enabled>false</enabled>
</snapshots>
<id>central</id>
<name>bintray</name>
<url>http://dl.bintray.com/robwin/maven</url>
</repository>
```

**Comment by RobWin** [comment]
Or better this one ?

```
<repositories>
<repository>
<snapshots>
<enabled>false</enabled>
</snapshots>
<id>central</id>
<name>bintray</name>
<url>http://jcenter.bintray.com</url>
</repository>
```

Definitely too many options.

**Comment by RobWin** [comment]
Beware that I had to rename the groupId, because of Maven Central guidlines.

**Comment by RobWin** [comment]
I will close the ticket.

Project is published in Maven Central now. 

https://oss.sonatype.org/#nexus-search;quick~robwin

Kind regards.
