### ISSUE TITLE
Parser does not like remote URL path with curly braces

### ISSUE THREAD

**Issue by gbaird** [RobWin/swagger2markup#10]
Not sure if this is an issue with this project or not. I am a novice. My API reads just fine for remote URL paths that do not have curly braces in them, however this occurs when they do. Apologies for the oversimplification, but this is all I can come up with:

java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8080/Walletron/api/api-docs/ver1/brands/{brand}/templates
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1626)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:46)
	at io.swagger.parser.SwaggerCompatConverter.readDeclaration(SwaggerCompatConverter.java:367)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:104)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:34)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:14)
	at io.github.robwin.swagger2markup.Swagger2MarkupConverter$Builder.<init>(Swagger2MarkupConverter.java:88)
	at io.github.robwin.swagger2markup.Swagger2MarkupConverter.from(Swagger2MarkupConverter.java:49)
	at io.github.robwin.swagger2markup.Swagger2MarkupConverterTest.testSwagger2AsciiDocConverter(Swagger2MarkupConverterTest.java:18)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
...

This repeats again and again for similar URLs, but the markdown is produced nicely for those paths without a parameter.

**Comment by gbaird** [comment]
You can try reading my Swagger JSON here: http://qa.walletron.com/api/api-docs

Thanks and great project!

-Garrett

**Comment by RobWin** [comment]
Hello,
the exceptions is thrown in the official SwaggerParser. But why does the server return a 500 HTTP Code? This does not seem to be a problem of the Parser, but of the server code?

Kind regards,
Robert

**Comment by gbaird** [comment]
The server is expecting the encoded URL, in this case: http://localhost:8080/Walletron/api/api-docs/ver1/brands/%7Bbrand%7D/templates  That works just fine and it appears browsers like Chrome  and cUrl utilities like Postman do this automatically. I am able however to reproduce the error on a straight curl from the command line.

Is there a config setting I'm missing to get swagger to encode this? Sorry to waste your time. :(

**Comment by RobWin** [comment]
Could you please address this issue in https://github.com/swagger-api/swagger-parser

**Comment by RobWin** [comment]
In my demo it works with Brackets 
```
{"apiVersion":"1.0","swaggerVersion":"1.2","basePath":"/","resourcePath":"/quotas","produces":["*/*"],"consumes":["application/json"],"apis":[{"path":"/quotas","description":"createMailStorageQuota","operations":[{"method":"PUT","summary":"Create a quota.","notes":"Create a quota allows bla bla bla bla","nickname":"createMailStorageQuota","produces":["*/*"],"consumes":["application/json"],"parameters":[{"allowMultiple":false,"defaultValue":"","description":"MailStorageQuota","name":"body","paramType":"body","type":"MailStorageQuota","required":true}],"responseMessages":[{"code":201,"message":"Created"},{"code":204,"message":null},{"code":401,"message":"Unauthorized"},{"code":403,"message":"Forbidden"},{"code":404,"message":"Not Found"}],"deprecated":"false","type":"void"}]},{"path":"/quotas/{quotaId}","description":"getMailStorageQuota","operations":[{"method":"GET","summary":"Get a quotas.","notes":"Get a quota allows bla bla bla bla","nickname":"getMailStorageQuota","produces":["*/*"],"consumes":["application/json"],"parameters":[{"allowMultiple":false,"defaultValue":"","description":"quotaId","name":"quotaId","paramType":"path","type":"string","required":true}],"responseMessages":[{"code":200,"message":"OK","responseModel":"MailStorageQuotaResponse"},{"code":401,"message":"Unauthorized"},{"code":403,"message":"Forbidden"},{"code":404,"message":"Not Found"}],"deprecated":"false","type":"MailStorageQuotaResponse"}]},{"path":"/quotas/{quotaId}","description":"deleteMailStorageQuota","operations":[{"method":"DELETE","summary":"Delete a quota.","notes":"Delete a quotas allows bla bla bla bla","nickname":"deleteMailStorageQuota","produces":["*/*"],"consumes":["application/json"],"parameters":[{"allowMultiple":false,"defaultValue":"","description":"quotaId","name":"quotaId","paramType":"path","type":"string","required":true}],"responseMessages":[{"code":204,"message":"No Content"},{"code":401,"message":"Unauthorized"},{"code":403,"message":"Forbidden"}],"deprecated":"false","type":"void"}]},{"path":"/quotas/{quotaId}","description":"updateMailStorageQuota","operations":[{"method":"POST","summary":"Update a quota.","notes":"Update a quota allows bla bla bla bla","nickname":"updateMailStorageQuota","produces":["*/*"],"consumes":["application/json"],"parameters":[{"allowMultiple":false,"defaultValue":"","description":"quotaId","name":"quotaId","paramType":"path","type":"string","required":true},{"allowMultiple":false,"defaultValue":"","description":"MailStorageQuota","name":"body","paramType":"body","type":"MailStorageQuota","required":true}],"responseMessages":[{"code":201,"message":"Created"},{"code":204,"message":null},{"code":401,"message":"Unauthorized"},{"code":403,"message":"Forbidden"},{"code":404,"message":"Not Found"}],"deprecated":"false","type":"void"}]}],"models":{"MailStorageQuota":{"description":"","id":"MailStorageQuota","properties":{"mailStorageQuotaValue":{"enum":["3","14","30","90","-1"],"required":false,"type":"string"},"quotaValueType":{"enum":["DEFAULT","CUSTOM"],"required":false,"type":"string"}}},"Void":{"description":"","id":"Void","properties":{}},"MailStorageQuotaResponse":{"description":"","id":"MailStorageQuotaResponse","properties":{"mailStorageQuota":{"required":false,"type":"MailStorageQuota"}}}}}
```

**Comment by gbaird** [comment]
Hmm, I'm using Jersey - here's an example:
There are the problematic curly braces in the middle of the Path...

@Path("ver1/brands/{brand}/templates")
@Api(value = "ver1/brands/{brand}/templates", description = "Communication Template Management")
@RequestScoped
public class TemplateRestApi {

    @GET
    @ApiOperation(value = "List existing communication templates", response = Template.class, responseContainer = "List")
    @ApiResponses(value = {
        @ApiResponse(code = 500, message = "Exception"),
        @ApiResponse(code = 404, message = "Not authorized")
    })
    @Produces(MediaType.APPLICATION_JSON)
    public Response getTemplatesByBrand(
    
    }


Looks like Swagger Parser MAY have addressed this in 1.0.1 but I'm not sure.

**Comment by RobWin** [comment]
Can't you do
```
@Path("ver1/brands/{brand}")
@Api(value = "ver1/brands/{brand}/templates", description = "Communication Template Management")
@RequestScoped
public class TemplateRestApi {
```

```
@GET("/templates")
@ApiOperation(value = "List existing communication templates", response = Template.class, responseContainer = "List")
@ApiResponses(value = {
    @ApiResponse(code = 500, message = "Exception"),
    @ApiResponse(code = 404, message = "Not authorized")
})
@Produces(MediaType.APPLICATION_JSON)
public Response getTemplatesByBrand(

}
```

**Comment by gbaird** [comment]
Unfortunately, Jersey doesn't like the duplicates that creates. I have several classes based on this "brand" entity. Here's an update over on the parser project that I believe will solve this problem: https://github.com/swagger-api/swagger-parser/pull/32

Thanks for your attention on this!

**Comment by RobWin** [comment]
You are welcome.
Feel free to give me your star ;-)
