### ISSUE TITLE
Boolean values 

### ISSUE THREAD

**Issue by neoecos** [RobWin/swagger2markup#15]
Hi @RobWin 

I found a weird error, i think is a bug in the swagger-core.

When any model have a "boolean" property it fails to parse the model (from the swagger.json)

The error is
```
com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"])
reading from docs/swagger/tpaga_api.json
com.fasterxml.jackson.databind.node.BooleanNode cannot be cast to com.fasterxml.jackson.databind.node.TextNode (through reference chain: com.wordnik.swagger.models.ModelImpl["properties"]) (through reference chain: com.wordnik.swagger.models.Swagger["definitions"])
```

**Comment by RobWin** [comment]
Hi 
Could you please show me your swagger.json?

**Comment by neoecos** [comment]
I just emailed it to you to the email in your profile.

**Comment by RobWin** [comment]
ok. I can reproduce the issue. 
The issue is in class com.wordnik.swagger.util.PropertyDeserializer in lines 73-75
```
 detailNode = node.get("default");
    if(detailNode != null)
      _default = (String) ((TextNode) detailNode).asText();
```

@neoecos Could you please open a ticket against swagger-core?

**Comment by RobWin** [comment]
Unfortunately I don't render the defaultValues in Markdown/AsciiDoc yet.

**Comment by RobWin** [comment]
Uh I see there is a new version of swagger-parser out now.

**Comment by RobWin** [comment]
You are lucky :)
The new swagger-parser supports default values now. I will implement this now.

**Comment by RobWin** [comment]
Implemented in v.0.6.0

**Comment by neoecos** [comment]
Thx!
