### ISSUE TITLE
MarkupLanguage cannot be resolved to a variable

### ISSUE THREAD

**Issue by yetti4** [RobWin/swagger2markup#2]
Hi,

Great library! I am trying to integrate it with swagger-springmvc 1.0 and spring 3.2.
From your example application the class MarkupLanguage (`io.github.robwin.swagger2markup.builder.markup.MarkupLanguage`) does not seem to exist in the maven package.
![capture](https://cloud.githubusercontent.com/assets/359682/6667971/3777aa60-cbf8-11e4-8372-5d61d5146e0a.PNG)

Moreover and maybe related, I get the following error message in pom.xml:
`Missing artifact io.github.robwin:markup-document-builder:jar:0.1.0`
I see that this version is already removed from the repository, but is still a dependency in build.gradle file.

Looking forward to integrate it with my solution.

Karens

**Comment by RobWin** [comment]
True it should be version 0.1.1 of the dependency.

**Comment by RobWin** [comment]
Gradle build file is fixed now.
THX.

**Comment by yetti4** [comment]
It compiles with including markup-document-builder 0.1.1 to pom.xml manually.
Tnx
