### ISSUE TITLE
Spring MVC integration example

### ISSUE THREAD

**Issue by yetti4** [RobWin/swagger2markup#4]
Hi,

I was wondering if you could provide an integration example without Spring Boot. It would be very useful for new users. Until now I could not get it to work.

Karens

**Comment by RobWin** [comment]
Hi,

how do you do End2End-Tests in your project?

Robert

**Comment by yetti4** [comment]
I am using PowerMock 1.5.4.
Until now I only added `@RunWith(PowerMockRunner.class)`

**Comment by RobWin** [comment]
Swagger2Markup requires a running application, which means you must deploy your Spring application in a servlet container like Tomcat or Jetty. 
Using Spring Boot it's easy to test your application. See my demo https://github.com/RobWin/spring-swagger2markup-demo.

If you use only the Spring Framework and Gradle, you could use https://github.com/akhikhl/gretty.

If you use maven, you could use http://arquillian.org/ and https://github.com/arquillian/arquillian-showcase/tree/master/spring

**Comment by yetti4** [comment]
I am using `org.springframework.web.servlet.DispatcherServlet` as server class in my web.xml  deployed on jboss server. This is already a running application, right?
I also use Maven.

**Comment by RobWin** [comment]
No. It's not a running application, if you only use @RunWith(PowerMockRunner.class).
As far as I know PowerMockRunner does not start the JBoss server.
If you use Spring JavaConfig, then have a look at https://github.com/arquillian/arquillian-showcase/tree/master/spring/spring-javaconfig/src/test/java/com/acme/spring/javaconfig

The Deployments class is important and in your test classs you must use: 

```
@RunWith(Arquillian.class)
@SpringAnnotationConfiguration(classes = StockConfig.class)
```

**Comment by RobWin** [comment]
Did it help you?

**Comment by yetti4** [comment]
I experimented yesterday with the setup, however I did not get it to work, due to old spring dependencies such `com.acme.*`. I think I will let it rest for a while because I do not feel comfortable to include arquillian in to my application.
Thanks a lot for your help though

**Comment by RobWin** [comment]
If you have a demo on Github I can have a look at it.

**Comment by yetti4** [comment]
No need to do so, it is not on github. Thanks for the offered help.
I might consider trying the swagger codegen library in the future.
