### ISSUE TITLE
How to use asciidoc to combine paths.adoc and definitions.adoc (with toc) as in the example

### ISSUE THREAD

**Issue by TuomasKiviaho** [RobWin/swagger2markup#5]
Hi,

I was wondering how you've produced the example with asciidoctor. I'm not familiar with the tool so would be kind to include provide a CLI or plugin based example of how to do this. 

--
Tuomas

**Comment by RobWin** [comment]
Hello,

I have a demo project https://github.com/RobWin/spring-swagger2markup-demo.
Is this what you mean?
The Gradle build file includes the full configuration of spring-restdocs and AsciiDoctorJ.

Kind regards,
Robert

**Comment by TuomasKiviaho** [comment]
Thanks for the pointer, but I was still how on earth the gradle plugin  knows to include both of the files. The attributes helped me and the I discovered that index.adoc is quite a common approach to handle file inclusions. Do you have some magic that created such a file, because I only got the paths and definitions separately. 
```
:doctype: book
:toc: left
:toclevels: 2
:numbered:

include::paths.adoc[] 
include::definitions.adoc[] 
```
I just created this one myself for now based on your example, because I noticed that swagger info was already processed at ``PathsDocument`` which was also level=0 document.

**Comment by RobWin** [comment]
No, there is not magic yet.
It depends on the documentation tool you use. Markdown does not support includes, but asciidoc does.
If you use http://www.mkdocs.org/ for example you have to do the includes differently than with AsciidoctorJ. That's why I don't create an index.adoc automatically yet.
