### ISSUE TITLE
@ApiModelProperty metadata are ignored for definitions file

### ISSUE THREAD

**Issue by lidkowiak** [RobWin/swagger2markup#7]
@ApiModelProperty("My description") 
private String myField;

results in 

 "MyType": {
      "description": "",
      "id": "MyType",
      "properties": {
        "myField": {
          "description": "My description",
          "required": false,
          "type": "string"
        }, 
...

and is ignored when creating definitions file.

**Comment by RobWin** [comment]
Thx for the issue.
I won't have much time within the next days. If you need it urgently, then please be free to create a Pull Request.

**Comment by RobWin** [comment]
Fixed in Version 0.2.3

**Comment by RobWin** [comment]
Fixed in Version 0.2.3
