### ISSUE TITLE
logback.xml on the classpath 

### ISSUE THREAD

**Issue by lidkowiak** [RobWin/swagger2markup#8]
Projects swagger2markup and markup-document-builder come with logback.xml on the classpath. For Spring Boot this is default location for logback configuration and Spring Boot uses this logback.xml when there is no logback configuration (defaults from Spring Boot is fine for development purposes).

**Comment by RobWin** [comment]
Correct. Thx.

**Comment by RobWin** [comment]
markup-document-builder is fixed in version 0.1.2

**Comment by RobWin** [comment]
Fixed in Version 0.2.3

**Comment by RobWin** [comment]
Fixed in v0.2.4
