### ISSUE TITLE
responseModel from api declaration is not rendered

### ISSUE THREAD

**Issue by lidkowiak** [RobWin/swagger2markup#9]
Here is json path to responseModel  : `/apis[*]/operations[*]/responseMessages[*]/responseModel`
It would be nice if this responseModel would be link to model in definitions section.

**Comment by RobWin** [comment]
Thx.
Yes, the whole Swagger Model/Definitions rendering must be refined in swagger2markup.

**Comment by yzatslinear** [comment]
+1 vote for this feature.

**Comment by gbaird** [comment]
+1

**Comment by RobWin** [comment]
Hi sry. I have much to do at work.
I hope I will have time soon.
PRs welcome ;-)

**Comment by RobWin** [comment]
Fixed in Version 0.2.3

**Comment by yzatslinear** [comment]
Thanks for the update. I tried the update code and see that that there are now links to definitions in the Responses table. Where are the definitions themselves ? The links appear to lead nowhere in my case.

**Comment by RobWin** [comment]
THX. I would like to know your opinion. Do you think it even makes sense to create separate files or would you prefer one file.
As a workaround you can use the method asString(). See readme example.

**Comment by yzatslinear** [comment]
I think a single file would be OK -- I'm not aware of any limitations this would present.

**Comment by RobWin** [comment]
@yzatslinear The approach with two files is to create an index.adoc which contains:

```
:doctype: book
:toc: left
:toclevels: 2
:numbered:

include::paths.adoc[] 
include::definitions.adoc[] 
```

and run AsciiDcotorJ (or the Gradle plugin). See build.gradle file as an example:

```
asciidoctor {
    sources {
        include 'index.adoc'
    }
    backends = ['html5', 'pdf']
    attributes = [
            doctype: 'book',
            toc: 'left',
            toclevels: '2',
            numbered: ''
    ]
}
```

The anchors in HTML work then. Unfortunately PDF seems to have a problem.

**Comment by RobWin** [comment]
I created an issue regarding the PDF issue.
asciidoctor/asciidoctorj#290

**Comment by yzatslinear** [comment]
Thanks @RobWin,
You say above that you include index.adoc into 0.2.4, but it doesn't appear it made it in ?

**Comment by RobWin** [comment]
The index.adoc is in /src/docs/asciidoc/

**Comment by yzatslinear** [comment]
Ah, makes sense. Thanks!
